/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as VendorRecommendationsRouteImport } from './routes/vendor.recommendations'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorInventoryRouteImport } from './routes/vendor.inventory'
import { Route as VendorForecastRouteImport } from './routes/vendor.forecast'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorCustomersRouteImport } from './routes/vendor.customers'
import { Route as VendorCustomerSegmentationRouteImport } from './routes/vendor.customer-segmentation'
import { Route as VendorCustomerAnalyticsRouteImport } from './routes/vendor.customer-analytics'
import { Route as VendorBusinessInsightsRouteImport } from './routes/vendor.business-insights'
import { Route as VendorBusinessDashboardRouteImport } from './routes/vendor.business-dashboard'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffRecommendationsRouteImport } from './routes/staff.recommendations'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffBusinessInsightsRouteImport } from './routes/staff.business-insights'
import { Route as StaffBusinessDashboardRouteImport } from './routes/staff.business-dashboard'
import { Route as ManagerUsersRouteImport } from './routes/manager.users'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerRecommendationsRouteImport } from './routes/manager.recommendations'
import { Route as ManagerNotificationsRouteImport } from './routes/manager.notifications'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerBusinessInsightsRouteImport } from './routes/manager.business-insights'
import { Route as ManagerBusinessDashboardRouteImport } from './routes/manager.business-dashboard'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerMarketplaceRouteImport } from './routes/customer.marketplace'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSystemDashboardRouteImport } from './routes/admin.system-dashboard'
import { Route as AdminSystemAuditRouteImport } from './routes/admin.system-audit'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminForecastRouteImport } from './routes/admin.forecast'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCustomerSegmentationRouteImport } from './routes/admin.customer-segmentation'
import { Route as AdminCustomerAnalyticsRouteImport } from './routes/admin.customer-analytics'
import { Route as AdminBusinessInsightsRouteImport } from './routes/admin.business-insights'
import { Route as AdminBusinessDashboardRouteImport } from './routes/admin.business-dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as VendorProductsIdRouteImport } from './routes/vendor.products.$id'
import { Route as VendorOrdersIdRouteImport } from './routes/vendor.orders.$id'
import { Route as AdminVendorsNewRouteImport } from './routes/admin.vendors.new'
import { Route as AdminVendorsIdRouteImport } from './routes/admin.vendors.$id'
import { Route as AdminTransactionsNewRouteImport } from './routes/admin.transactions.new'
import { Route as AdminTransactionsIdRouteImport } from './routes/admin.transactions.$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminInventoryIdRouteImport } from './routes/admin.inventory.$id'
import { Route as VendorProductsIdEditRouteImport } from './routes/vendor.products.$id.edit'
import { Route as AdminVendorsIdEditRouteImport } from './routes/admin.vendors.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRecommendationsRoute = VendorRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInventoryRoute = VendorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => VendorRoute,
} as any)
const VendorForecastRoute = VendorForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => VendorRoute,
} as any)
const VendorCustomerSegmentationRoute =
  VendorCustomerSegmentationRouteImport.update({
    id: '/customer-segmentation',
    path: '/customer-segmentation',
    getParentRoute: () => VendorRoute,
  } as any)
const VendorCustomerAnalyticsRoute = VendorCustomerAnalyticsRouteImport.update({
  id: '/customer-analytics',
  path: '/customer-analytics',
  getParentRoute: () => VendorRoute,
} as any)
const VendorBusinessInsightsRoute = VendorBusinessInsightsRouteImport.update({
  id: '/business-insights',
  path: '/business-insights',
  getParentRoute: () => VendorRoute,
} as any)
const VendorBusinessDashboardRoute = VendorBusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRecommendationsRoute = StaffRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBusinessInsightsRoute = StaffBusinessInsightsRouteImport.update({
  id: '/business-insights',
  path: '/business-insights',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBusinessDashboardRoute = StaffBusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const ManagerUsersRoute = ManagerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerRecommendationsRoute = ManagerRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerNotificationsRoute = ManagerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBusinessInsightsRoute = ManagerBusinessInsightsRouteImport.update({
  id: '/business-insights',
  path: '/business-insights',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBusinessDashboardRoute =
  ManagerBusinessDashboardRouteImport.update({
    id: '/business-dashboard',
    path: '/business-dashboard',
    getParentRoute: () => ManagerRoute,
  } as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMarketplaceRoute = CustomerMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemDashboardRoute = AdminSystemDashboardRouteImport.update({
  id: '/system-dashboard',
  path: '/system-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemAuditRoute = AdminSystemAuditRouteImport.update({
  id: '/system-audit',
  path: '/system-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastRoute = AdminForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerSegmentationRoute =
  AdminCustomerSegmentationRouteImport.update({
    id: '/customer-segmentation',
    path: '/customer-segmentation',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomerAnalyticsRoute = AdminCustomerAnalyticsRouteImport.update({
  id: '/customer-analytics',
  path: '/customer-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessInsightsRoute = AdminBusinessInsightsRouteImport.update({
  id: '/business-insights',
  path: '/business-insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessDashboardRoute = AdminBusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VendorProductsRoute,
} as any)
const VendorProductsIdRoute = VendorProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorProductsRoute,
} as any)
const VendorOrdersIdRoute = VendorOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const AdminVendorsNewRoute = AdminVendorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVendorsRoute,
} as any)
const AdminVendorsIdRoute = AdminVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVendorsRoute,
} as any)
const AdminTransactionsNewRoute = AdminTransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTransactionsRoute,
} as any)
const AdminTransactionsIdRoute = AdminTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTransactionsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminInventoryIdRoute = AdminInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const VendorProductsIdEditRoute = VendorProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VendorProductsIdRoute,
} as any)
const AdminVendorsIdEditRoute = AdminVendorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminVendorsIdRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminProductsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business-dashboard': typeof AdminBusinessDashboardRoute
  '/admin/business-insights': typeof AdminBusinessInsightsRoute
  '/admin/customer-analytics': typeof AdminCustomerAnalyticsRoute
  '/admin/customer-segmentation': typeof AdminCustomerSegmentationRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-audit': typeof AdminSystemAuditRoute
  '/admin/system-dashboard': typeof AdminSystemDashboardRoute
  '/admin/transactions': typeof AdminTransactionsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/marketplace': typeof CustomerMarketplaceRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/manager/business-dashboard': typeof ManagerBusinessDashboardRoute
  '/manager/business-insights': typeof ManagerBusinessInsightsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/recommendations': typeof ManagerRecommendationsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/business-dashboard': typeof StaffBusinessDashboardRoute
  '/staff/business-insights': typeof StaffBusinessInsightsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/recommendations': typeof StaffRecommendationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/business-dashboard': typeof VendorBusinessDashboardRoute
  '/vendor/business-insights': typeof VendorBusinessInsightsRoute
  '/vendor/customer-analytics': typeof VendorCustomerAnalyticsRoute
  '/vendor/customer-segmentation': typeof VendorCustomerSegmentationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/forecast': typeof VendorForecastRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/recommendations': typeof VendorRecommendationsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/products/$id': typeof AdminProductsIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/transactions/new': typeof AdminTransactionsNewRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRouteWithChildren
  '/admin/vendors/new': typeof AdminVendorsNewRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/$id': typeof VendorProductsIdRouteWithChildren
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/vendors/$id/edit': typeof AdminVendorsIdEditRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business-dashboard': typeof AdminBusinessDashboardRoute
  '/admin/business-insights': typeof AdminBusinessInsightsRoute
  '/admin/customer-analytics': typeof AdminCustomerAnalyticsRoute
  '/admin/customer-segmentation': typeof AdminCustomerSegmentationRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-audit': typeof AdminSystemAuditRoute
  '/admin/system-dashboard': typeof AdminSystemDashboardRoute
  '/admin/transactions': typeof AdminTransactionsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/marketplace': typeof CustomerMarketplaceRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/manager/business-dashboard': typeof ManagerBusinessDashboardRoute
  '/manager/business-insights': typeof ManagerBusinessInsightsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/recommendations': typeof ManagerRecommendationsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/business-dashboard': typeof StaffBusinessDashboardRoute
  '/staff/business-insights': typeof StaffBusinessInsightsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/recommendations': typeof StaffRecommendationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/business-dashboard': typeof VendorBusinessDashboardRoute
  '/vendor/business-insights': typeof VendorBusinessInsightsRoute
  '/vendor/customer-analytics': typeof VendorCustomerAnalyticsRoute
  '/vendor/customer-segmentation': typeof VendorCustomerSegmentationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/forecast': typeof VendorForecastRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/recommendations': typeof VendorRecommendationsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/products/$id': typeof AdminProductsIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/transactions/new': typeof AdminTransactionsNewRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRouteWithChildren
  '/admin/vendors/new': typeof AdminVendorsNewRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/$id': typeof VendorProductsIdRouteWithChildren
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/vendors/$id/edit': typeof AdminVendorsIdEditRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business-dashboard': typeof AdminBusinessDashboardRoute
  '/admin/business-insights': typeof AdminBusinessInsightsRoute
  '/admin/customer-analytics': typeof AdminCustomerAnalyticsRoute
  '/admin/customer-segmentation': typeof AdminCustomerSegmentationRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forecast': typeof AdminForecastRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-audit': typeof AdminSystemAuditRoute
  '/admin/system-dashboard': typeof AdminSystemDashboardRoute
  '/admin/transactions': typeof AdminTransactionsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/marketplace': typeof CustomerMarketplaceRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/manager/business-dashboard': typeof ManagerBusinessDashboardRoute
  '/manager/business-insights': typeof ManagerBusinessInsightsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/recommendations': typeof ManagerRecommendationsRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/business-dashboard': typeof StaffBusinessDashboardRoute
  '/staff/business-insights': typeof StaffBusinessInsightsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/recommendations': typeof StaffRecommendationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/business-dashboard': typeof VendorBusinessDashboardRoute
  '/vendor/business-insights': typeof VendorBusinessInsightsRoute
  '/vendor/customer-analytics': typeof VendorCustomerAnalyticsRoute
  '/vendor/customer-segmentation': typeof VendorCustomerSegmentationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/forecast': typeof VendorForecastRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/recommendations': typeof VendorRecommendationsRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/products/$id': typeof AdminProductsIdRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/transactions/new': typeof AdminTransactionsNewRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRouteWithChildren
  '/admin/vendors/new': typeof AdminVendorsNewRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/$id': typeof VendorProductsIdRouteWithChildren
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/vendors/$id/edit': typeof AdminVendorsIdEditRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/manager'
    | '/profile'
    | '/register'
    | '/staff'
    | '/vendor'
    | '/admin/analytics'
    | '/admin/business-dashboard'
    | '/admin/business-insights'
    | '/admin/customer-analytics'
    | '/admin/customer-segmentation'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-audit'
    | '/admin/system-dashboard'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vendors'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/dashboard'
    | '/customer/marketplace'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/support'
    | '/customer/wishlist'
    | '/manager/business-dashboard'
    | '/manager/business-insights'
    | '/manager/dashboard'
    | '/manager/notifications'
    | '/manager/recommendations'
    | '/manager/reports'
    | '/manager/users'
    | '/staff/business-dashboard'
    | '/staff/business-insights'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/recommendations'
    | '/staff/reports'
    | '/vendor/analytics'
    | '/vendor/business-dashboard'
    | '/vendor/business-insights'
    | '/vendor/customer-analytics'
    | '/vendor/customer-segmentation'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/forecast'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/recommendations'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/vendor/'
    | '/admin/inventory/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/transactions/$id'
    | '/admin/transactions/new'
    | '/admin/vendors/$id'
    | '/admin/vendors/new'
    | '/vendor/orders/$id'
    | '/vendor/products/$id'
    | '/vendor/products/new'
    | '/admin/products/$id/edit'
    | '/admin/vendors/$id/edit'
    | '/vendor/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/business-dashboard'
    | '/admin/business-insights'
    | '/admin/customer-analytics'
    | '/admin/customer-segmentation'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-audit'
    | '/admin/system-dashboard'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vendors'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/dashboard'
    | '/customer/marketplace'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/support'
    | '/customer/wishlist'
    | '/manager/business-dashboard'
    | '/manager/business-insights'
    | '/manager/dashboard'
    | '/manager/notifications'
    | '/manager/recommendations'
    | '/manager/reports'
    | '/manager/users'
    | '/staff/business-dashboard'
    | '/staff/business-insights'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/recommendations'
    | '/staff/reports'
    | '/vendor/analytics'
    | '/vendor/business-dashboard'
    | '/vendor/business-insights'
    | '/vendor/customer-analytics'
    | '/vendor/customer-segmentation'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/forecast'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/recommendations'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/admin'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/vendor'
    | '/admin/inventory/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/transactions/$id'
    | '/admin/transactions/new'
    | '/admin/vendors/$id'
    | '/admin/vendors/new'
    | '/vendor/orders/$id'
    | '/vendor/products/$id'
    | '/vendor/products/new'
    | '/admin/products/$id/edit'
    | '/admin/vendors/$id/edit'
    | '/vendor/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/manager'
    | '/profile'
    | '/register'
    | '/staff'
    | '/vendor'
    | '/admin/analytics'
    | '/admin/business-dashboard'
    | '/admin/business-insights'
    | '/admin/customer-analytics'
    | '/admin/customer-segmentation'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forecast'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-audit'
    | '/admin/system-dashboard'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/vendors'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/dashboard'
    | '/customer/marketplace'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/support'
    | '/customer/wishlist'
    | '/manager/business-dashboard'
    | '/manager/business-insights'
    | '/manager/dashboard'
    | '/manager/notifications'
    | '/manager/recommendations'
    | '/manager/reports'
    | '/manager/users'
    | '/staff/business-dashboard'
    | '/staff/business-insights'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/staff/recommendations'
    | '/staff/reports'
    | '/vendor/analytics'
    | '/vendor/business-dashboard'
    | '/vendor/business-insights'
    | '/vendor/customer-analytics'
    | '/vendor/customer-segmentation'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/forecast'
    | '/vendor/inventory'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/recommendations'
    | '/vendor/reports'
    | '/vendor/settings'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/vendor/'
    | '/admin/inventory/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/transactions/$id'
    | '/admin/transactions/new'
    | '/admin/vendors/$id'
    | '/admin/vendors/new'
    | '/vendor/orders/$id'
    | '/vendor/products/$id'
    | '/vendor/products/new'
    | '/admin/products/$id/edit'
    | '/admin/vendors/$id/edit'
    | '/vendor/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/recommendations': {
      id: '/vendor/recommendations'
      path: '/recommendations'
      fullPath: '/vendor/recommendations'
      preLoaderRoute: typeof VendorRecommendationsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/inventory': {
      id: '/vendor/inventory'
      path: '/inventory'
      fullPath: '/vendor/inventory'
      preLoaderRoute: typeof VendorInventoryRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/forecast': {
      id: '/vendor/forecast'
      path: '/forecast'
      fullPath: '/vendor/forecast'
      preLoaderRoute: typeof VendorForecastRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/customer-segmentation': {
      id: '/vendor/customer-segmentation'
      path: '/customer-segmentation'
      fullPath: '/vendor/customer-segmentation'
      preLoaderRoute: typeof VendorCustomerSegmentationRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/customer-analytics': {
      id: '/vendor/customer-analytics'
      path: '/customer-analytics'
      fullPath: '/vendor/customer-analytics'
      preLoaderRoute: typeof VendorCustomerAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/business-insights': {
      id: '/vendor/business-insights'
      path: '/business-insights'
      fullPath: '/vendor/business-insights'
      preLoaderRoute: typeof VendorBusinessInsightsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/business-dashboard': {
      id: '/vendor/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/vendor/business-dashboard'
      preLoaderRoute: typeof VendorBusinessDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/recommendations': {
      id: '/staff/recommendations'
      path: '/recommendations'
      fullPath: '/staff/recommendations'
      preLoaderRoute: typeof StaffRecommendationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/business-insights': {
      id: '/staff/business-insights'
      path: '/business-insights'
      fullPath: '/staff/business-insights'
      preLoaderRoute: typeof StaffBusinessInsightsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/business-dashboard': {
      id: '/staff/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/staff/business-dashboard'
      preLoaderRoute: typeof StaffBusinessDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/recommendations': {
      id: '/manager/recommendations'
      path: '/recommendations'
      fullPath: '/manager/recommendations'
      preLoaderRoute: typeof ManagerRecommendationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/notifications': {
      id: '/manager/notifications'
      path: '/notifications'
      fullPath: '/manager/notifications'
      preLoaderRoute: typeof ManagerNotificationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/business-insights': {
      id: '/manager/business-insights'
      path: '/business-insights'
      fullPath: '/manager/business-insights'
      preLoaderRoute: typeof ManagerBusinessInsightsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/business-dashboard': {
      id: '/manager/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/manager/business-dashboard'
      preLoaderRoute: typeof ManagerBusinessDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/marketplace': {
      id: '/customer/marketplace'
      path: '/marketplace'
      fullPath: '/customer/marketplace'
      preLoaderRoute: typeof CustomerMarketplaceRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-dashboard': {
      id: '/admin/system-dashboard'
      path: '/system-dashboard'
      fullPath: '/admin/system-dashboard'
      preLoaderRoute: typeof AdminSystemDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-audit': {
      id: '/admin/system-audit'
      path: '/system-audit'
      fullPath: '/admin/system-audit'
      preLoaderRoute: typeof AdminSystemAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecast': {
      id: '/admin/forecast'
      path: '/forecast'
      fullPath: '/admin/forecast'
      preLoaderRoute: typeof AdminForecastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-segmentation': {
      id: '/admin/customer-segmentation'
      path: '/customer-segmentation'
      fullPath: '/admin/customer-segmentation'
      preLoaderRoute: typeof AdminCustomerSegmentationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-analytics': {
      id: '/admin/customer-analytics'
      path: '/customer-analytics'
      fullPath: '/admin/customer-analytics'
      preLoaderRoute: typeof AdminCustomerAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business-insights': {
      id: '/admin/business-insights'
      path: '/business-insights'
      fullPath: '/admin/business-insights'
      preLoaderRoute: typeof AdminBusinessInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business-dashboard': {
      id: '/admin/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/admin/business-dashboard'
      preLoaderRoute: typeof AdminBusinessDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorProductsRoute
    }
    '/vendor/products/$id': {
      id: '/vendor/products/$id'
      path: '/$id'
      fullPath: '/vendor/products/$id'
      preLoaderRoute: typeof VendorProductsIdRouteImport
      parentRoute: typeof VendorProductsRoute
    }
    '/vendor/orders/$id': {
      id: '/vendor/orders/$id'
      path: '/$id'
      fullPath: '/vendor/orders/$id'
      preLoaderRoute: typeof VendorOrdersIdRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/admin/vendors/new': {
      id: '/admin/vendors/new'
      path: '/new'
      fullPath: '/admin/vendors/new'
      preLoaderRoute: typeof AdminVendorsNewRouteImport
      parentRoute: typeof AdminVendorsRoute
    }
    '/admin/vendors/$id': {
      id: '/admin/vendors/$id'
      path: '/$id'
      fullPath: '/admin/vendors/$id'
      preLoaderRoute: typeof AdminVendorsIdRouteImport
      parentRoute: typeof AdminVendorsRoute
    }
    '/admin/transactions/new': {
      id: '/admin/transactions/new'
      path: '/new'
      fullPath: '/admin/transactions/new'
      preLoaderRoute: typeof AdminTransactionsNewRouteImport
      parentRoute: typeof AdminTransactionsRoute
    }
    '/admin/transactions/$id': {
      id: '/admin/transactions/$id'
      path: '/$id'
      fullPath: '/admin/transactions/$id'
      preLoaderRoute: typeof AdminTransactionsIdRouteImport
      parentRoute: typeof AdminTransactionsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/inventory/$id': {
      id: '/admin/inventory/$id'
      path: '/$id'
      fullPath: '/admin/inventory/$id'
      preLoaderRoute: typeof AdminInventoryIdRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/vendor/products/$id/edit': {
      id: '/vendor/products/$id/edit'
      path: '/edit'
      fullPath: '/vendor/products/$id/edit'
      preLoaderRoute: typeof VendorProductsIdEditRouteImport
      parentRoute: typeof VendorProductsIdRoute
    }
    '/admin/vendors/$id/edit': {
      id: '/admin/vendors/$id/edit'
      path: '/edit'
      fullPath: '/admin/vendors/$id/edit'
      preLoaderRoute: typeof AdminVendorsIdEditRouteImport
      parentRoute: typeof AdminVendorsIdRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsIdRoute
    }
  }
}

interface AdminInventoryRouteChildren {
  AdminInventoryIdRoute: typeof AdminInventoryIdRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryIdRoute: AdminInventoryIdRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminProductsIdRouteChildren {
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsIdRouteChildren: AdminProductsIdRouteChildren = {
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsIdRouteWithChildren = AdminProductsIdRoute._addFileChildren(
  AdminProductsIdRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRouteWithChildren
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRouteWithChildren,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminTransactionsRouteChildren {
  AdminTransactionsIdRoute: typeof AdminTransactionsIdRoute
  AdminTransactionsNewRoute: typeof AdminTransactionsNewRoute
}

const AdminTransactionsRouteChildren: AdminTransactionsRouteChildren = {
  AdminTransactionsIdRoute: AdminTransactionsIdRoute,
  AdminTransactionsNewRoute: AdminTransactionsNewRoute,
}

const AdminTransactionsRouteWithChildren =
  AdminTransactionsRoute._addFileChildren(AdminTransactionsRouteChildren)

interface AdminVendorsIdRouteChildren {
  AdminVendorsIdEditRoute: typeof AdminVendorsIdEditRoute
}

const AdminVendorsIdRouteChildren: AdminVendorsIdRouteChildren = {
  AdminVendorsIdEditRoute: AdminVendorsIdEditRoute,
}

const AdminVendorsIdRouteWithChildren = AdminVendorsIdRoute._addFileChildren(
  AdminVendorsIdRouteChildren,
)

interface AdminVendorsRouteChildren {
  AdminVendorsIdRoute: typeof AdminVendorsIdRouteWithChildren
  AdminVendorsNewRoute: typeof AdminVendorsNewRoute
}

const AdminVendorsRouteChildren: AdminVendorsRouteChildren = {
  AdminVendorsIdRoute: AdminVendorsIdRouteWithChildren,
  AdminVendorsNewRoute: AdminVendorsNewRoute,
}

const AdminVendorsRouteWithChildren = AdminVendorsRoute._addFileChildren(
  AdminVendorsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBusinessDashboardRoute: typeof AdminBusinessDashboardRoute
  AdminBusinessInsightsRoute: typeof AdminBusinessInsightsRoute
  AdminCustomerAnalyticsRoute: typeof AdminCustomerAnalyticsRoute
  AdminCustomerSegmentationRoute: typeof AdminCustomerSegmentationRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForecastRoute: typeof AdminForecastRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemAuditRoute: typeof AdminSystemAuditRoute
  AdminSystemDashboardRoute: typeof AdminSystemDashboardRoute
  AdminTransactionsRoute: typeof AdminTransactionsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBusinessDashboardRoute: AdminBusinessDashboardRoute,
  AdminBusinessInsightsRoute: AdminBusinessInsightsRoute,
  AdminCustomerAnalyticsRoute: AdminCustomerAnalyticsRoute,
  AdminCustomerSegmentationRoute: AdminCustomerSegmentationRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForecastRoute: AdminForecastRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemAuditRoute: AdminSystemAuditRoute,
  AdminSystemDashboardRoute: AdminSystemDashboardRoute,
  AdminTransactionsRoute: AdminTransactionsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerMarketplaceRoute: typeof CustomerMarketplaceRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerMarketplaceRoute: CustomerMarketplaceRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface ManagerRouteChildren {
  ManagerBusinessDashboardRoute: typeof ManagerBusinessDashboardRoute
  ManagerBusinessInsightsRoute: typeof ManagerBusinessInsightsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerNotificationsRoute: typeof ManagerNotificationsRoute
  ManagerRecommendationsRoute: typeof ManagerRecommendationsRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerUsersRoute: typeof ManagerUsersRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBusinessDashboardRoute: ManagerBusinessDashboardRoute,
  ManagerBusinessInsightsRoute: ManagerBusinessInsightsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerNotificationsRoute: ManagerNotificationsRoute,
  ManagerRecommendationsRoute: ManagerRecommendationsRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerUsersRoute: ManagerUsersRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface StaffRouteChildren {
  StaffBusinessDashboardRoute: typeof StaffBusinessDashboardRoute
  StaffBusinessInsightsRoute: typeof StaffBusinessInsightsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffRecommendationsRoute: typeof StaffRecommendationsRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBusinessDashboardRoute: StaffBusinessDashboardRoute,
  StaffBusinessInsightsRoute: StaffBusinessInsightsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffRecommendationsRoute: StaffRecommendationsRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface VendorOrdersRouteChildren {
  VendorOrdersIdRoute: typeof VendorOrdersIdRoute
}

const VendorOrdersRouteChildren: VendorOrdersRouteChildren = {
  VendorOrdersIdRoute: VendorOrdersIdRoute,
}

const VendorOrdersRouteWithChildren = VendorOrdersRoute._addFileChildren(
  VendorOrdersRouteChildren,
)

interface VendorProductsIdRouteChildren {
  VendorProductsIdEditRoute: typeof VendorProductsIdEditRoute
}

const VendorProductsIdRouteChildren: VendorProductsIdRouteChildren = {
  VendorProductsIdEditRoute: VendorProductsIdEditRoute,
}

const VendorProductsIdRouteWithChildren =
  VendorProductsIdRoute._addFileChildren(VendorProductsIdRouteChildren)

interface VendorProductsRouteChildren {
  VendorProductsIdRoute: typeof VendorProductsIdRouteWithChildren
  VendorProductsNewRoute: typeof VendorProductsNewRoute
}

const VendorProductsRouteChildren: VendorProductsRouteChildren = {
  VendorProductsIdRoute: VendorProductsIdRouteWithChildren,
  VendorProductsNewRoute: VendorProductsNewRoute,
}

const VendorProductsRouteWithChildren = VendorProductsRoute._addFileChildren(
  VendorProductsRouteChildren,
)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorBusinessDashboardRoute: typeof VendorBusinessDashboardRoute
  VendorBusinessInsightsRoute: typeof VendorBusinessInsightsRoute
  VendorCustomerAnalyticsRoute: typeof VendorCustomerAnalyticsRoute
  VendorCustomerSegmentationRoute: typeof VendorCustomerSegmentationRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorForecastRoute: typeof VendorForecastRoute
  VendorInventoryRoute: typeof VendorInventoryRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRouteWithChildren
  VendorProductsRoute: typeof VendorProductsRouteWithChildren
  VendorProfileRoute: typeof VendorProfileRoute
  VendorRecommendationsRoute: typeof VendorRecommendationsRoute
  VendorReportsRoute: typeof VendorReportsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorBusinessDashboardRoute: VendorBusinessDashboardRoute,
  VendorBusinessInsightsRoute: VendorBusinessInsightsRoute,
  VendorCustomerAnalyticsRoute: VendorCustomerAnalyticsRoute,
  VendorCustomerSegmentationRoute: VendorCustomerSegmentationRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorForecastRoute: VendorForecastRoute,
  VendorInventoryRoute: VendorInventoryRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRouteWithChildren,
  VendorProductsRoute: VendorProductsRouteWithChildren,
  VendorProfileRoute: VendorProfileRoute,
  VendorRecommendationsRoute: VendorRecommendationsRoute,
  VendorReportsRoute: VendorReportsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
